- name: "Splatoon 2"
  id: "461029893858131968"
  top:
    - "Playing casual"
    - "Playing ranked"
    - "Playing league"
    - "Playing salmon run"
    - "In lobby"
  bot:
    - ""
    - "In a Group (1 of 8)"
    - "In a Group (2 of 8)"
    - "In a Group (3 of 8)"
    - "In a Group (4 of 8)"
    - "In a Group (5 of 8)"
    - "In a Group (6 of 8)"
    - "In a Group (7 of 8)"
    - "In a Group (8 of 8)"

- name: "Zelda: BotW"
  id: "461408978400706570"
  top:
    - "Adventuring in Hyrule"
  bot:
    - ""

- name: "Super Smash Bros. Ultimate"
  id: "461414353791483904"
  top:
    - "In Menus"
    - "Playing For Fun"
    - "Playing For Glory"
  bot:
    - "In a Group (1 of 4)"
    - "In a Group (2 of 4)"
    - "In a Group (3 of 4)"
    - "In a Group (4 of 4)"
